### ISSUE TITLE
modal cookie

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#1]
I think it was mentioned that the modal on the front-page is using localstorage to determine is a user has closed the modal already and to not show it again if that's the case.

Localstorage is a good idea, however it sounds like it wasn't working on some browsers.
If you want to try a more browser-friendly solution you could try using cookies instead.

e.g. 
https://codepen.io/Yogatopia/pen/LGOQpL

**Comment by ghost** [comment]
if (localStorage.getItem('popState') !== 'shown') {
            $popupOverlay.delay(2000).fadeIn().focus();
            $('html > .home').css('overflow', 'hidden');
            _**localStorage.setItem('popState', 'shown');**_
           }

Hey Jim, we added the line that has been bolded which was not there before. Now it appears to be working on all browsers. Prior to that we didn't have that line and it was only working on chrome but for now all seems good.
