### ISSUE TITLE
footer.php date

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#10]
In the footer the year is hardcoded, this is ok for now but as soon as 2018 hits we would have to remember to change this manually.

PHP has a very nice date function we could use for this instead, e.g.

```<p>copyright &copy; <?php echo date("Y"); ?> East Van Roasters all rights reserved</p>```

**Comment by ghost** [comment]
done

**Comment by rcass** [comment]
Looks great 🎉
