### ISSUE TITLE
Make email into a mailto link

### ISSUE THREAD

**Issue by rcass** [redacademy/evr-summer-2017#15]
This is just bonus, but if your team thinks it is appropriate, turning the contact email from text to a mailto link.

So basically, a user could click the email to start a email to that particular address.
![screen shot 2017-09-19 at 9 33 48 am](https://user-images.githubusercontent.com/5028555/30603910-e1595e22-9d1d-11e7-9847-d56bce099d14.png)

**Comment by temefleet** [comment]
The email address is now a 'mailto' link.

**Comment by rcass** [comment]
perfecto 🌮
