### ISSUE TITLE
functions.php organization suggestion

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#2]
Something you could try...

I usually like to organize this file by having actions/hooks etc... at the top, along with includes.

e.g. 

// includes
require get_template_directory() . '/inc/template-tags.php';
require get_template_directory() . '/inc/extras.php';

// hooks & filters
add_action( 'widgets_init', 'evr_widgets_init' );
add_filter( 'stylesheet_uri', 'evr_minified_css', 10, 2 );

// then functions

**Comment by ghost** [comment]
done
