### ISSUE TITLE
CFS sanitize output

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#4]
On line 44 of archive-workshop.php
Generally with CFS or other things we are getting from the database we can sanitize the output using some WordPress functions e.g.

```<img class="workshop-image content-image" src="<?php echo CFS()->get( 'workshop_image' ) ?>">```
could be used with esc_url

```<img class="workshop-image content-image" src="<?php echo esc_url( CFS()->get( 'workshop_image' ) ) ?>">```

**Comment by ghost** [comment]
done

**Comment by rcass** [comment]
Be sure to do this through out the entire theme (and well plugins too).
For example, in menu.php there are some CFS calls that have no been sanitized

Close this when you are sure you sanitized the output across the whole theme!

**Comment by temefleet** [comment]
I had missed sanitising the plugins, but now I believe everything has been sanitised.

**Comment by rcass** [comment]
Looks good to me 👍
