### ISSUE TITLE
modal click closing

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#8]
I'm not sure if the latest script file is being used, maybe try gulp scripts to be sure.

On the front-page the popup modal looks great, but when I try to click on the form the modal disappears.
When viewing the compiled file: http://evr.cp.academy.red/wp-content/themes/evr/build/js/modal-subscribe.min.js?ver=1.0

I noticed there's a click event for p.click(function
Not sure why that's there, the js file looks like it just has the one click ```$('#close-popup').click(function () {```

**Comment by ghost** [comment]
this has been fixed.
